version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: web
    ports:
      - "2306:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: toys
      MYSQL_USER: thuyht
      MYSQL_PASSWORD: thuyht@123
      MYSQL_ROOT_PASSWORD: thuyht@A123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '2106:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db