version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "06:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: assignment2_autoshop
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '2381.80'
    restart: always
    environment:
      PMA_HOST: db
    depends-on:
      - db